FROM jenkins/jenkins:lts

USER root

# Install Python, Docker CLI, Node (for ARM Sonar Scanner), and dependencies
RUN apt update && \
    apt install -y python3 python3-venv python3-pip docker.io npm curl unzip && \
    npm install -g sonarqube-scanner && \
    ln -sf /usr/local/bin/sonarqube-scanner /usr/local/bin/sonar-scanner || true && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
