pipeline {
  agent any

  environment {
    DOCKER_REPO = "aceest-fitness"
    IMAGE_TAG   = "${env.BUILD_NUMBER}"
    SONAR_HOST_URL = "http://sonarqube:9000"
    SONAR_TOKEN    = credentials('sonarqube-token')
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Setup Python') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
        '''
      }
    }

    stage('Unit Tests') {
      steps {
        sh '''
          . .venv/bin/activate
          pytest -q --cov=app --cov-report=xml --junitxml=pytest.xml
        '''
      }
      post {
        always {
          junit 'pytest.xml'
        }
      }
    }

    
    
    stage('SonarQube Analysis') {
        steps {
            withSonarQubeEnv('sonarqube') {
            sh '''
                WORKSPACE_PATH=$(pwd)
                echo "Sonar working directory: $WORKSPACE_PATH"

                # Run SonarScanner container and copy workspace into it
                CONTAINER_ID=$(docker create --network cicd-net \
                -e SONAR_HOST_URL=$SONAR_HOST_URL \
                -e SONAR_TOKEN=$SONAR_AUTH_TOKEN \
                sonarsource/sonar-scanner-cli:latest)

                echo "Copying workspace into scanner container..."
                docker cp $WORKSPACE_PATH/. $CONTAINER_ID:/usr/src/

                echo "Starting scan..."
                docker start -a $CONTAINER_ID sh -c "
                cd /usr/src &&
                ls -R &&
                sonar-scanner \
                    -Dsonar.projectKey=aceest-fitness \
                    -Dsonar.sources=app \
                    -Dsonar.tests=tests \
                    -Dsonar.python.version=3.11 \
                    -Dsonar.python.coverage.reportPaths=coverage.xml
                "

                docker rm -f $CONTAINER_ID || true
            '''
            }
        }
    }





    stage('Build Docker Image') {
      steps {
        sh """
          docker build -t ${DOCKER_REPO}:${IMAGE_TAG} .
        """
      }
    }

    stage('Run Container (Verification)') {
        steps {
            sh '''
            docker rm -f aceest-test || true
            docker run -d --network cicd-net -p 5050:5000 --name aceest-test ${DOCKER_REPO}:${IMAGE_TAG}

            echo "Waiting for container to start..."
            sleep 15

            curl -f http://aceest-test:5000/health || curl -f http://localhost:5050/health

            docker stop aceest-test && docker rm aceest-test
            '''
        }
    }



  }

  post {
    success {
      echo "✅ Build ${env.BUILD_NUMBER} completed successfully!"
    }
    failure {
      echo "❌ Build failed. Check logs for details."
    }
  }
}

